name: Discord Notifications

on:
  push:
  pull_request:
    types: [closed] # Optional: can remove this too if you no longer need PR triggers
  issues:
    types: [opened]
  release:
    types: [published]
  watch:
    types: [started]
  fork:
  discussion:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Push Notification
        if: github.event_name == 'push'
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                 \"embeds\": [{
                   \"title\": \"New Push to **${{ github.repository }}**\",
                   \"description\": \"${{ github.actor }} pushed commits to \`${{ github.ref_name }}\`\",
                   \"color\": 3447003,
                   \"url\": \"https://github.com/${{ github.repository }}/commit/${{ github.sha }}\",
                   \"footer\": { \"text\": \"DevSync • GitHub\" }
                 }]
               }" \
               "${{ secrets.DISCORD_WEBHOOK }}"

      - name: Issue Opened Notification
        if: github.event_name == 'issues' && github.event.action == 'opened'
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                 \"embeds\": [{
                   \"title\": \"New Issue Opened\",
                   \"description\": \"**${{ github.event.issue.title }}**\n\n${{ github.event.issue.body }}\",
                   \"color\": 15105570,
                   \"author\": {
                     \"name\": \"${{ github.event.issue.user.login }}\",
                     \"icon_url\": \"${{ github.event.issue.user.avatar_url }}\"
                   },
                   \"url\": \"${{ github.event.issue.html_url }}\",
                   \"footer\": { \"text\": \"DevSync • GitHub\" }
                 }]
               }" \
               "${{ secrets.DISCORD_WEBHOOK }}"

      - name: Release Published Notification
        if: github.event_name == 'release' && github.event.action == 'published'
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                 \"embeds\": [{
                   \"title\": \"New Release: ${{ github.event.release.tag_name }}\",
                   \"description\": \"${{ github.event.release.body }}\",
                   \"color\": 8311585,
                   \"url\": \"${{ github.event.release.html_url }}\",
                   \"footer\": { \"text\": \"DevSync • GitHub\" }
                 }]
               }" \
               "${{ secrets.DISCORD_WEBHOOK }}"

      - name: Star Added Notification
        if: github.event_name == 'watch' && github.event.action == 'started'
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                 \"embeds\": [{
                   \"title\": \"⭐ New Star on Repo!\",
                   \"description\": \"${{ github.actor }} starred **${{ github.repository }}**\",
                   \"color\": 16776960,
                   \"url\": \"https://github.com/${{ github.repository }}\",
                   \"footer\": { \"text\": \"DevSync • GitHub\" }
                 }]
               }" \
               "${{ secrets.DISCORD_WEBHOOK }}"

      - name: Fork Created Notification
        if: github.event_name == 'fork'
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                 \"embeds\": [{
                   \"title\": \"🍴 Repository Forked!\",
                   \"description\": \"${{ github.actor }} forked **${{ github.repository }}**\",
                   \"color\": 10181046,
                   \"url\": \"https://github.com/${{ github.repository }}\",
                   \"footer\": { \"text\": \"DevSync • GitHub\" }
                 }]
               }" \
               "${{ secrets.DISCORD_WEBHOOK }}"

      - name: Discussion Created Notification
        if: github.event_name == 'discussion' && github.event.action == 'created'
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                 \"embeds\": [{
                   \"title\": \"💬 New Discussion Started\",
                   \"description\": \"**${{ github.event.discussion.title }}**\n\n${{ github.event.discussion.body }}\",
                   \"color\": 15277667,
                   \"author\": {
                     \"name\": \"${{ github.event.discussion.user.login }}\",
                     \"icon_url\": \"${{ github.event.discussion.user.avatar_url }}\"
                   },
                   \"url\": \"${{ github.event.discussion.html_url }}\",
                   \"footer\": { \"text\": \"DevSync • GitHub\" }
                 }]
               }" \
               "${{ secrets.DISCORD_WEBHOOK }}"
