name: Discord Notifications

on:
  pull_request:
    types: [opened, closed, reopened, ready_for_review, review_requested, synchronize]

  pull_request_review:
    types: [submitted, edited, dismissed]

  issues:
    types: [opened, closed, reopened, assigned, unassigned, labeled, unlabeled]

  issue_comment:
    types: [created, edited, deleted]

  push:
    branches: [main, develop]

  release:
    types: [published, unpublished, created, edited, deleted, prereleased, released]

  fork:

  watch:
    types: [started]

  discussion:
    types: [created, edited, deleted, pinned, unpinned, locked, unlocked, transferred, answered, unanswered]

  discussion_comment:
    types: [created, edited, deleted]

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
    - name: Set up notification content
      id: setup
      run: |
        case "${{ github.event_name }}" in
          "pull_request")
            case "${{ github.event.action }}" in
              "opened") EMOJI="🔀"; COLOR="3066993"; TITLE="New Pull Request Opened";;
              "closed")
                if [ "${{ github.event.pull_request.merged }}" == "true" ]; then
                  EMOJI="✅"; COLOR="5763719"; TITLE="Pull Request Merged"
                else
                  EMOJI="❌"; COLOR="15158332"; TITLE="Pull Request Closed"
                fi;;
              "reopened") EMOJI="🔄"; COLOR="3066993"; TITLE="Pull Request Reopened";;
              "ready_for_review") EMOJI="👀"; COLOR="3066993"; TITLE="Pull Request Ready for Review";;
              "review_requested") EMOJI="🔍"; COLOR="15844367"; TITLE="Review Requested";;
              "synchronize") EMOJI="🔄"; COLOR="3066993"; TITLE="Pull Request Updated";;
            esac;;
          "pull_request_review")
            case "${{ github.event.action }}" in
              "submitted")
                case "${{ github.event.review.state }}" in
                  "approved") EMOJI="✅"; COLOR="5763719"; TITLE="Pull Request Approved";;
                  "changes_requested") EMOJI="🔄"; COLOR="15844367"; TITLE="Changes Requested";;
                  "commented") EMOJI="💬"; COLOR="3066993"; TITLE="Review Comment Added";;
                esac;;
            esac;;
          "issues")
            case "${{ github.event.action }}" in
              "opened") EMOJI="🐛"; COLOR="15158332"; TITLE="New Issue Opened";;
              "closed") EMOJI="✅"; COLOR="5763719"; TITLE="Issue Closed";;
              "reopened") EMOJI="🔄"; COLOR="15158332"; TITLE="Issue Reopened";;
              "assigned") EMOJI="👤"; COLOR="3066993"; TITLE="Issue Assigned";;
            esac;;
          "issue_comment") EMOJI="💬"; COLOR="3066993"; TITLE="New Comment on Issue";;
          "push") EMOJI="📝"; COLOR="7506394"; TITLE="New Commits Pushed";;
          "release")
            case "${{ github.event.action }}" in
              "published") EMOJI="🎉"; COLOR="5763719"; TITLE="New Release Published";;
              "prereleased") EMOJI="🚀"; COLOR="15844367"; TITLE="Pre-release Published";;
            esac;;
          "fork") EMOJI="🍴"; COLOR="3066993"; TITLE="Repository Forked";;
          "watch") EMOJI="⭐"; COLOR="15844367"; TITLE="Repository Starred";;
          "discussion")
            case "${{ github.event.action }}" in
              "created") EMOJI="💭"; COLOR="3066993"; TITLE="New Discussion Created";;
              "answered") EMOJI="✅"; COLOR="5763719"; TITLE="Discussion Answered";;
            esac;;
          *) EMOJI="📢"; COLOR="3066993"; TITLE="GitHub Event";;
        esac

        echo "EMOJI=$EMOJI" >> $GITHUB_OUTPUT
        echo "COLOR=$COLOR" >> $GITHUB_OUTPUT
        echo "TITLE=$TITLE" >> $GITHUB_OUTPUT

    - name: Send Discord Notification
      run: |
        jq -n --arg title "${{ steps.setup.outputs.TITLE }}" \
              --arg desc "${{ github.event.pull_request.title || github.event.issue.title || github.event.head_commit.message || github.event.release.name || github.event.discussion.title }}" \
              --arg body "${{ github.event.pull_request.body || github.event.issue.body || github.event.comment.body || github.event.review.body || github.event.release.body || github.event.discussion.body }}" \
              --arg repo "${{ github.repository }}" \
              --arg url "${{ github.event.pull_request.html_url || github.event.issue.html_url || github.event.comment.html_url || github.event.head_commit.url || github.event.release.html_url || github.event.discussion.html_url }}" \
              --argjson color ${{ steps.setup.outputs.COLOR }} \
              '{
                "embeds": [{
                  "title": $title,
                  "description": ($desc + "\n\n" + $body),
                  "color": $color,
                  "fields": [{
                    "name": "Repository", "value": $repo, "inline": true
                  }],
                  "url": $url,
                  "footer": {
                    "text": "DevSync • GitHub",
                    "icon_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
                  }
                }]
              }' | curl -H "Content-Type: application/json" -X POST -d @- "${{ secrets.DISCORD_WEBHOOK }}"