name: Issue Greetings

on:
  issues:
    types: [assigned]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write 
    steps:
      - name: Add greeting comment
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `🎉 Thank you @${context.payload.assignee?.login || context.payload.issue.user.login} for picking up this issue!  
              Please make sure to follow our contributing guidelines here 👉 [Contributing Guidelines](https://github.com/DevSyncx/DevSync/blob/main/CONTRIBUTING.md)
              Happy coding !!
              and Don't forget to give this repo a 🌟`
            })
